import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import './sales-workspace.css';
export default function OperationsDashboard() {
  const [stats,setStats] = useState(null), [error,setError] = useState('');
  useEffect(() => { api.get('/leads/stats').then(r => setStats(r.data)).catch(() => setError('Dashboard data could not be loaded. Refresh to retry.')); }, []);
  const won = stats?.statusCounts.find(s => s.status === 'won')?.count || 0;
  return <div className="sw-root"><header className="sw-heading"><div><span className="sw-kicker">MEET YOUR NEEDS · CRVM SUIT</span><h1>Sales operations overview</h1><p>Prospects, vendor records and recorded sales progress.</p></div><Link className="sw-primary" to="/leads">Open sales desk →</Link></header>{error && <p className="sw-alert" role="alert">{error}</p>}{!stats && !error && <p>Loading saved data…</p>}{stats && <><div className="sw-prospect-grid">{[['Sales prospects',stats.salesLeadCount,'Saved business records; interest requires qualification.'],['Vendor records',stats.vendorCount,'Suppliers in the register; approval requires review.'],['Recorded won deals',won,'Based on recorded CRM stage.']].map(([name,value,note]) => <section className="sw-panel" key={name}><span className="sw-kicker">{name}</span><h1>{value}</h1><p className="sw-muted">{note}</p></section>)}</div><div className="sw-two-columns"><section className="sw-panel"><h2>Active estimated pipeline</h2><h1>₹{Number(stats.pipelineValue).toLocaleString('en-IN')}</h1><p className="sw-muted">Recorded estimated values for open sales prospects. Excludes vendors and won/lost records. This is not booked revenue.</p><Link to="/pipeline">Review deal stages →</Link></section><section className="sw-panel sw-guide"><span className="sw-kicker">TODAY’S SALES ROUTINE</span><h2>Read. Call. Record. Follow up.</h2><p>Open a lead’s business profile, check its source and read the suggested pitch. Record the actual outcome and the next agreed date.</p><Link style={{color:'#ccff19'}} to="/reports">Review follow-ups and daily report →</Link></section></div><section className="sw-panel sw-table-wrap"><div className="sw-heading"><h2>Recent additions</h2><Link to="/reports">Full daily report →</Link></div><table><thead><tr><th>Date (UTC)</th><th>New prospects</th><th>New vendors</th></tr></thead><tbody>{stats.dailyCounts.slice(-7).reverse().map(row => <tr key={row.date}><td>{row.date}</td><td>{row.salesLeads}</td><td>{row.vendors}</td></tr>)}</tbody></table>{!stats.dailyCounts.length && <p>No source or manual records have been saved yet.</p>}<p className="sw-muted">The detailed daily report uses India time. Figures here reflect the original intake statistics.</p></section></>}</div>;
}
