import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, CheckCircle2, ExternalLink, ShieldCheck } from 'lucide-react';
import api from '../services/api';
import './sales-workspace.css';
export default function SourceSync() {
  const [status,setStatus] = useState(null), [error,setError] = useState(''), [busy,setBusy] = useState(false), [result,setResult] = useState(null);
  const load = () => api.get('/sales/automation').then(r => setStatus(r.data));
  useEffect(() => { load().catch(() => setError('Connection status unavailable. Please refresh.')); }, []);
  async function sync() {
    setBusy(true); setError(''); setResult(null);
    try { const {data} = await api.post('/integrations/make/sync', {limit:50}); setResult(data.counts); await load(); }
    catch(e) { setError(e.response?.data?.error || 'Sync failed. No success has been confirmed.'); }
    finally { setBusy(false); }
  }
  return <div className="sw-root"><header className="sw-heading"><div><span className="sw-kicker">SOURCE CONNECTION & RUN HISTORY</span><h1>Synchronize records</h1><p>See what is connected and what each run actually saved.</p></div><Link to="/leads">View prospects →</Link></header>{error && <p className="sw-alert" role="alert">{error}</p>}
    <section className="sw-panel"><span className="sw-pill">{status ? status.configured ? 'Live acquisition connected' : 'Setup required' : 'Checking connection…'}</span><h2>Make acquisition connection</h2><p>{status?.message}</p><div className="sw-target"><strong>Current target</strong><span>Hyderabad business prospects only</span><small>Free OpenStreetMap/Overpass businesses → Make → Hyderabad filter → CRVM. Vendor records and other cities are rejected by this intake.</small></div>
      <div className="sw-source-warning"><AlertTriangle size={17} /><div><strong>Apify is disabled.</strong><p>The old scenario is inactive and must not be run. It used a paid scraper and did not prove Hyderabad leads.</p></div></div>
      <p className="sw-muted">Runs the source scenario now, caps the intake at 10 Hyderabad businesses, checks duplicates, and imports only records actually returned by Make. Empty results stay empty; no fake records are created.</p><button className="sw-primary" disabled={!status?.configured || busy} onClick={sync}>{busy ? 'Acquiring Hyderabad leads…' : 'Synchronize Hyderabad leads'}</button><p><a href="https://eu1.make.com/1963743/scenarios/7214839" target="_blank" rel="noreferrer">Open Make scenario ↗ <ExternalLink size={13} /></a></p></section>
    <section className="sw-panel"><div className="sw-row"><h2>Free-source replacement plan</h2><span className="sw-pill"><ShieldCheck size={14} /> No Apify</span></div><div className="sw-training-grid"><article><h3><CheckCircle2 size={16} /> OpenStreetMap / Overpass</h3><p>Free public business-directory data. Good for Hyderabad company names and locations; phone/email coverage is incomplete, so these are prospects to verify.</p></article><article><h3><CheckCircle2 size={16} /> Foursquare Places</h3><p>Optional free developer tier with a token. It can return place records, but it is still a source account and volume is not guaranteed.</p></article><article><h3><CheckCircle2 size={16} /> LinkedIn official Lead Sync</h3><p>Only Lead Gen Form, Page, Event, or approved LinkedIn API leads can be connected. Profile scraping and automatic connection messages are not enabled.</p></article></div><p className="sw-muted">The safe flow is: source → Hyderabad filter → duplicate key → CRVM webhook → salesperson call guide → daily report.</p></section>
    {result && <section className="sw-panel" role="status"><h2>Acquisition result</h2><p>Acquired: {result.acquired ?? 0} · Received: {result.received} · New: {result.created} · Duplicates skipped: {result.duplicates} · Rejected: {result.rejected}</p><p>New records are prospects until their requirements have been confirmed.</p></section>}<section className="sw-panel sw-table-wrap"><h2>Recent runs</h2><table><thead><tr><th>Started (UTC)</th><th>Status</th><th>Received</th><th>New</th><th>Duplicates</th><th>Rejected</th></tr></thead><tbody>{status?.runs.map(run => <tr key={run.id}><td>{run.startedAt}</td><td>{run.status}</td><td>{run.received}</td><td>{run.created}</td><td>{run.duplicates}</td><td>{run.rejected}</td></tr>)}</tbody></table>{status && !status.runs.length && <p>No runs recorded by the updated integration.</p>}</section></div>;
}
